apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: s3
  labels:
    app: minio
spec:
  replicas: 2
  serviceName: minio-headless
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ce
            # local version
            #- mkdir -p /data/li-oam /data/smf-li-oam /data/upf-li-oam && /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /data
            # cluster version
            - mkdir -p /data/li-oam /data/smf-li-oam /data/upf-li-oam && /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server https://minio-{0...1}.minio-headless.s3.svc.quick3:9000/data
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-aws-keys
                  key: accessKeyId
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-aws-keys
                  key: secretAccessKey
            - name: MINIO_CONSOLE_ADDRESS
              value: 0.0.0.0:9200
          ports:
            - containerPort: 9000
              name: https
              protocol: TCP
            - containerPort: 9200
              name: https-console
              protocol: TCP
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m    
          volumeMounts:
            - name: minio-data
              mountPath: /data
            - name: certs
              mountPath: /etc/minio/certs/
              readOnly: true
            - name: trusted-cas
              mountPath: /etc/minio/certs/CAs
              readOnly: true 
      volumes:
        - name: minio-aws-keys
          secret:
            secretName: minio-aws-keys
        - name: certs
          secret:
            #defaultMode: 420
            items:
              - key: tls.crt
                path: public.crt
              - key: tls.key
                path: private.key
            secretName: minio-tls
        - name: trusted-cas
          secret:
            #defaultMode: 420
            items:
              - key: ca.crt
                path: public.crt
            secretName: minio-tls
  volumeClaimTemplates:
    - metadata:
        name: minio-data
        namespace: s3
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: "ganesha-nfs"
        resources:
          requests:
            storage: 5Gi