apiVersion: v1
kind: Secret
type: kubernetes.io/opaque
metadata:
  name: minio-aws-keys
  namespace: s3
data:
  accessKeyId: bWluaW8=
  secretAccessKey: bWluaW9taW5pbw==
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
  namespace: s3
spec:
  secretName: minio-tls
  usages:
  - "digital signature"
  - "key encipherment"
  dnsNames:
  - "minio"
  - "minio-data.s3.svc.cluster.local"
  - "minio-console.s3.svc.cluster.local"
  - "172.0.3.3"
  - "*.minio-headless.s3.svc.cluster.local"
  issuerRef:
    name: akley-common-issuer
    kind: ClusterIssuer