apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: s3
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: data
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: console
---
apiVersion: v1
kind: Service
metadata:
  name: minio-data
  namespace: s3
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32002
      protocol: TCP
      name: data
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: s3
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 32003
      protocol: TCP
      name: console
  selector:
    app: minio
    apps.kubernetes.io/pod-index: "0"