{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: eg-minio-console
spec:
  parentRefs:
  - name: eg-public
    namespace: gateway
    sectionName: https
  hostnames:
  - "minio-console.agf.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ printf "%s-console" (include "minio.fullname" .) }}
      kind: Service
      port: {{ .Values.service.console.port }}
---
# apiVersion: gateway.envoyproxy.io/v1alpha1
# kind: Backend
# metadata:
#   name: eg-minio-tls-backend
# spec:
#   endpoints:
#     - fqdn:
#         hostname: {{ printf "%s-console.%s" (include "minio.fullname" .) (include "minio.svcDomainSuffix" .) }}
#         port: 9200
#   tls:
#     insecureSkipVerify: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: eg-minio-tls-backend
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: {{ printf "%s-console" (include "minio.fullname" .) }}
    sectionName: console
  validation:
    caCertificateRefs:
    - name: {{ .Values.cert.secretName }}
      group: ''
      kind: Secret
    hostname: {{ printf "%s-console.%s" (include "minio.fullname" .) (include "minio.svcDomainSuffix" .) }}
{{- end }}